version: "3.5"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
      mode: non-blocking
      max-buffer-size: 4m
      loki-retries: "3"
services:
  replaydemo-client:
    <<: *logging
    build:
      dockerfile: Dockerfile
    image: replaydemo-client:latest
    ports:
      - 19993:9995